### ISSUE TITLE
tapeout project is overwriting Chipyard build.sbt settings

### ISSUE THREAD

**Issue by tymcauley** [ucb-bar/barstools#117]
I originally filed this issue in Chipyard, and there's some useful context there: https://github.com/ucb-bar/chipyard/issues/1103

It looks like the definition of a `tapeout` project (the `lazy val tapeout = (project ...)` line) in this repo's `build.sbt` file causes conflicts with parent repos when barstools is used in a multi-project SBT setup (like Chipyard). In the case of Chipyard, all of Chipyard's `tapeout` project settings are getting overwritten by the `tapeout`  project settings in this repo's `build.sbt` file, so users can't customize the `tapeout` project definition in Chipyard. For my use-case, I'd like to add a dependency on another Chipyard project which contains some FIRRTL transforms. However, those cross-project dependencies get removed by the `tapeout` project definition in this repo's `build.sbt` file.

I'm not quite familiar enough with this project to know if this will cause issues, but it appears that removing the `tapeout` project from this repo's `build.sbt` file and making all of the settings unscoped resolves this conflict. For instance, the `build.sbt` file for this project could look something like this:

```scala
val defaultVersions = Map(
  "chisel3" -> "3.5-SNAPSHOT",
  "chisel-iotesters" -> "2.5-SNAPSHOT"
)

organization := "edu.berkeley.cs"
version := "0.4-SNAPSHOT"
name := "tapeout"
scalaVersion := "2.12.13"
fork := true
scalacOptions := Seq("-deprecation", "-feature", "-language:reflectiveCalls")
Test / scalacOptions ++= Seq("-language:reflectiveCalls")
mainClass := Some("barstools.macros.MacroCompiler")
libraryDependencies ++= Seq("chisel3","chisel-iotesters").map {
  dep: String => "edu.berkeley.cs" %% dep % sys.props.getOrElse(dep + "Version", defaultVersions(dep))
}
libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-json" % "2.9.2",
  "org.scalatest" %% "scalatest" % "3.2.9" % "test",
  "org.apache.logging.log4j" % "log4j-api" % "2.11.2",
  "org.apache.logging.log4j" % "log4j-core" % "2.11.2"
)
resolvers ++= Seq(
  Resolver.sonatypeRepo("snapshots"),
  Resolver.sonatypeRepo("releases"),
  Resolver.mavenLocal
)
```

This means when you enter the `sbt` console in this project, you are already in the `tapeout` project, and you wouldn't have to run the `project tapeout` command before running commands like `runMain barstools.tapeout.transforms.GenerateTop ...`. Does this seem like an okay solution?

**Comment by abejgonzalez** [comment]
I think this seems reasonable. I think having a specific project specified was originally done since there used to be multiple subprojects under this repo. However, that was deprecated in https://github.com/ucb-bar/barstools/pull/109. If you PR it, I'll go ahead and run the Chipyard CI on it.

**Comment by tymcauley** [comment]
Awesome, thanks @abejgonzalez! Just added the PR: #118.
