### ISSUE TITLE
Renaming of ext mems in TestHarness

### ISSUE THREAD

**Issue by alonamid** [ucb-bar/barstools#60]
Some of the ext mems in the test harness are not getting renamed, and this is causing duplicate declarations of mems (verilator/vcs very unhappy). 
Seems like this issue manifested in EagleX, and @colinschmidt hacked it in the Makefile using a `sed`, but this should probably get a firrtl fix.
This also manifested in the systolic branch of chipyard where it can be reproduced on hash 4a76d16 (the makefile hack is applied after that hash)
@azidar

**Comment by abejgonzalez** [comment]
Solved with https://github.com/ucb-bar/barstools/pull/63
